name: release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies and build
        run: |
          python3 -m pip install --upgrade pip build
          cd mpcontribs-client
          python3 -m build --outdir ../dist

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1.5
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: ./dist/
